---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: engagements
spec:
  count: 1
  elasticsearchRef:
    name: engagements
  version: 7.14.0
  podTemplate:
    metadata:
      labels:
        foo: bar
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              memory: 1Gi
              cpu: 250m
            limits:
              memory: 2Gi
              cpu: 1
  http:
    service:
      metadata:
        annotations:
          service.beta.openshift.io/serving-cert-secret-name: "kibana-openshift-tls"
    tls:
      certificate:
        secretName: kibana-openshift-tls
