{{- if .Values.route }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "document-loader-service.fullname" . }}
  labels:
    {{- include "document-loader-service.labels" . | nindent 4 }}
spec:
  port:
    targetPort: proxy
  to:
    kind: Service
    name: {{ include "document-loader-service.fullname" . }}
    weight: 100
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - status: 'True'
          type: Admitted
{{ end }}
