---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "document-loader-service.fullname" . }}
  labels:
    {{- include "document-loader-service.labels" . | nindent 4 }}
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.document-loader-service-admin: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"document-loader-service"}}'
