---
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: opendatahub-trino
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        parameters:
          # Note: The admin username is admin
          - name: SUPERSET_ADMIN_PASSWORD
            value: admin
          - name: SUPERSET_IMAGE
            value: quay.io/internaldatahub/superset:1.1.0-trino
        repoRef:
          name: manifests
          path: superset
      name: superset
    - kustomizeConfig:
        parameters:
          - name: s3_endpoint_url
            value: "minio-ml-workshop.ml-workshop:9000"
        repoRef:
          name: manifests
          path: jupyterhub/jupyterhub
      name: jupyterhub
    - kustomizeConfig:
        overlays:
          #- cuda
          - additional
        repoRef:
          name: manifests
          path: jupyterhub/notebook-images
      name: notebook-images
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: airflow/operator
      name: airflow-operator
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: airflow/cluster
      name: airflow-cluster
    - kustomizeConfig:
        overlays:
          - ml-workshop
        parameters:
          - name: s3_endpoint_url
            value: >-
              minio-ml-workshop.ml-workshop:9000
          - name: s3_credentials_secret
            value: s3-credentials
          - name: s3_endpoint_url_prefix
            value: "http://"
        repoRef:
          name: manifests
          path: trino
      name: trino
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: ml-workshop-minio
      name: minio
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: ml-workshop-airflow
      name: ml-airflow
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: ml-workshop-custom-images
      name: ml-workshop-images
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: ml-workshop-mlflow
      name: ml-workshop-mlflow
  repos:
    - name: kf-manifests
      uri: https://github.com/kubeflow/manifests/archive/v1.2-branch.tar.gz
    - name: manifests
      uri: https://github.com/eformat/odh-manifests/tarball/master
  version: master
